test:
  path: /test/{age} #  /test/{age<\d+>?0}
  controller: App\Controller\TestController::test
  defaults:
    age: 0
    requirements:
      age: \d+
        method: [GET]
        # host: monsite.com / www.monsite.com ou {sundomain}.monsite.com
        # schemes: [https,http]